### ISSUE TITLE
asyncio ImportError

### ISSUE THREAD

**Issue by Adnios** [ms-jpq/markdown-preview#16]
Hello. I met an error while trying to run `mlp`. It is caused by asyncio. What's version of asyncio do you use?
```bash
$ mlp
Traceback (most recent call last):
  File "/home/scrutiny/.local/bin/mlp", line 4, in <module>
    from asyncio import run
ImportError: cannot import name 'run'
```
```bash
$  pip list | grep asyncio
asyncio                           3.4.3
```
By the way, your colorscheme of vim is pretty. What's the name of your colorscheme?

**Comment by ms-jpq** [comment]
sorry you have to use 3.8, it seems like you are 3.6 or lower? :d
