### ISSUE TITLE
mlp command doesn't work on windows

### ISSUE THREAD

**Issue by GnikDroy** [ms-jpq/markdown-preview#81]
Currently the mlp file in windows looks like:

```python
#!C:\Python310\python.exe

from markdown_live_preview import __main__
```

The shebang contains the path to the python interpreter. Shebangs are invalid of course.

One way to solve this is by using a `.bat` or `.cmd` file on windows. So use `mlp.bat` or `mlp.cmd` and use

```bat
C:\Python310\python.exe -m markdown_live_preview %*
```
**Replace** the example absolute path with the actual absolute path. It is **necessary** to write the absolute path due to virtual environments.

**Comment by ms-jpq** [comment]
i think i fixed it using the new pyproject.toml

please reopen if still borked
